### ISSUE TITLE
Urgent bug

### ISSUE THREAD

**Issue by jacobwi** [NexusRisen/NASCAR-Texas-Super-Speedway#1]
Crashes the server when going up north. Possibly not loading the object correctly.

**Comment by Wyste** [comment]
Just tried this yesterday, 11/13 - can confirm it crashes the client's game when getting near the alamo sea.

**Comment by jacobwi** [comment]
I found the problem. It is probably caused by MapMaker resource. They would have to wipe their server files and start fresh.
